In [2]:
import torch
from tabpfn import TabPFNClassifier

print(torch.__version__)
clf = TabPFNClassifier(device="cpu")
print("TabPFN OK")

2.10.0+cpu
TabPFN OK


In [3]:
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split

import os
# os.environ["HF_TOKEN"] = "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"

os.environ["HF_HOME"] = r"D:\Users\zyxf\.cache\huggingface"
os.environ["HF_HUB_OFFLINE"] = "1"
os.environ["TRANSFORMERS_OFFLINE"] = "1"

from tabpfn import TabPFNClassifier
from tabpfn.constants import ModelVersion
import numpy as np


In [ ]:
# 小样本，故意制造不稳定
np.random.seed(0)

X_train = np.random.randn(30, 5)
y_train = (X_train[:, 0] + 0.5 * X_train[:, 1] > 0).astype(int)

X_test = np.random.randn(5, 5)
model = TabPFNClassifier(
    device="cpu",
    model_path=r"D:\Users\zyxf\.cache\huggingface\hub\models--Prior-Labs--tabpfn_2_5\snapshots\main\tabpfn-v2.5-classifier-v2.5_default-2.ckpt"
)

model.fit(X_train, y_train) 
proba = model.predict_proba(X_test)

print(proba)


[[0.05327797 0.94672203]
 [0.65653753 0.34346247]
 [0.18493019 0.81506985]
 [0.15923107 0.8407689 ]
 [0.00808609 0.9919139 ]]


In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, precision_score, recall_score
from sklearn.model_selection import train_test_split
from tabpfn import TabPFNClassifier

# Load data
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

# Initialize TabPFN
clf = TabPFNClassifier(
    device="cpu",
    model_path=r"D:\Users\zyxf\.cache\huggingface\hub\models--Prior-Labs--tabpfn_2_5\snapshots\main\tabpfn-v2.5-classifier-v2.5_default-2.ckpt"
)
clf.fit(X_train, y_train)  

# Predict probabilities
y_proba = clf.predict_proba(X_test)
roc_auc = roc_auc_score(y_test, y_proba[:, 1])
print("ROC AUC:", roc_auc)

# Predict labels
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# 混淆矩阵
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# 精确率和召回率
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
print("Precision:", precision)
print("Recall:", recall)


d:\Users\zyxf\AppData\Local\Programs\Python\Python311\Lib\site-packages\tabpfn\validation.py:56: UserWarning: Running on CPU with more than 200 samples may be slow.
Consider using a GPU or the tabpfn-client API: https://github.com/PriorLabs/tabpfn-client
  _validate_num_samples_for_cpu(


ROC AUC: 0.9978718760231365
Accuracy: 0.9824561403508771
Confusion Matrix:
 [[ 97   1]
 [  4 183]]
Precision: 0.9945652173913043
Recall: 0.9786096256684492


In [ ]:
y_proba

array([[5.40952869e-02, 9.45904732e-01],
       [9.99992371e-01, 7.59428531e-06],
       [9.99921858e-01, 7.81810959e-05],
       [2.87294006e-05, 9.99971271e-01],
       [4.48054052e-05, 9.99955237e-01],
       [9.99937773e-01, 6.22134539e-05],
       [9.99985158e-01, 1.48666304e-05],
       [9.83121037e-01, 1.68789458e-02],
       [2.61495888e-01, 7.38504112e-01],
       [1.32341331e-04, 9.99867678e-01],
       [1.05436193e-02, 9.89456356e-01],
       [9.99759853e-01, 2.40165755e-04],
       [7.09998421e-04, 9.99289989e-01],
       [9.70142603e-01, 2.98574120e-02],
       [2.71259667e-03, 9.97287393e-01],
       [9.96575296e-01, 3.42470314e-03],
       [1.66263650e-04, 9.99833763e-01],
       [6.23002270e-05, 9.99937713e-01],
       [8.95851190e-05, 9.99910414e-01],
       [9.99996603e-01, 3.38474001e-06],
       [2.95576099e-02, 9.70442414e-01],
       [1.45904114e-03, 9.98540938e-01],
       [9.99993443e-01, 6.61287049e-06],
       [1.14983988e-04, 9.99885023e-01],
       [8.297612

In [5]:
y_proba[:, 1]

array([9.45904732e-01, 7.59428531e-06, 7.81810959e-05, 9.99971271e-01,
       9.99955237e-01, 6.22134539e-05, 1.48666304e-05, 1.68789458e-02,
       7.38504112e-01, 9.99867678e-01, 9.89456356e-01, 2.40165755e-04,
       9.99289989e-01, 2.98574120e-02, 9.97287393e-01, 3.42470314e-03,
       9.99833763e-01, 9.99937713e-01, 9.99910414e-01, 3.38474001e-06,
       9.70442414e-01, 9.98540938e-01, 6.61287049e-06, 9.99885023e-01,
       9.99170184e-01, 9.95276928e-01, 9.99940515e-01, 9.97961283e-01,
       9.99856710e-01, 1.38603491e-05, 9.99780238e-01, 9.99978542e-01,
       9.81105089e-01, 9.98890340e-01, 9.99987900e-01, 9.98779655e-01,
       1.20210703e-02, 9.44314599e-01, 3.04593482e-06, 9.87513006e-01,
       9.99988198e-01, 8.76075137e-05, 9.99697149e-01, 9.99902070e-01,
       5.60774565e-01, 9.06329513e-01, 9.99516189e-01, 9.97340739e-01,
       9.37059104e-01, 9.99488711e-01, 5.45074590e-06, 3.16386240e-06,
       4.02152181e-01, 8.56574595e-01, 9.99947965e-01, 9.94491577e-01,
      